logging:
  file: C:/logs/dev/spring-boot-detail.log

db:
  connection:
    urlmaster: jdbc:postgresql://127.0.0.1:5432/SpringBootDB
    urlslave: jdbc:postgresql://127.0.0.1:5432/SlaveSpringBootDB
    username: noah
    password: 123456